name: CICD

on:
  push:
    branches: [ "live_server" ]
  pull_request:
    branches: [ "live_server" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: live_server
      - name: install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build SpringBoot Server
        run: |
          echo ${{ secrets.APPLICATION_SECRET }} | base64 --decode > ./src/main/resources/application-secret.yml
          chmod 700 ./mvnw
          ./mvnw clean package -Dtestskip

      - name: Show Directory
        run: |
          ls -al
          cd ./target
          ls -al

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/live_server .

      - name: Push DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest
